# Generated by Django 5.1 on 2024-09-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0002_menuitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems",
            old_name="course",
            new_name="category",
        ),
    ]
