# Generated by Django 5.1 on 2024-09-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0004_rename_name_menuitems_itemname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drink", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
