# Generated by Django 5.1 on 2024-09-01 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0006_rename_drink_drinks_drink_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_category_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Menus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_item", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                (
                    "category_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="menuapp.menucategory",
                    ),
                ),
            ],
        ),
    ]
