# Generated by Django 5.1 on 2024-09-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0007_menucategory_menus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="category_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_name",
                to="menuapp.menucategory",
            ),
        ),
    ]
